# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.example.org".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.
groupName: acmedns.example.org

certManager:
  serviceAccountName: cert-manager
  namespace: cert-manager

image:
  repository: ghcr.io/katter/cert-manager-webhook-desec-http
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

secretName:
- cert-manager-desec-http-secret

resources:
  limits:
     cpu: 250m
     memory: 256Mi
  requests:
     cpu: 250m
     memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

## Webhook pods' Security Context.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
podSecurityContext:
  enabled: true
  fsGroup: 1001

## Webhook Core containers' Security Context (only main container).
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
##
containerSecurityContext:
  enabled: true
  runAsUser: 1001
  readOnlyRootFilesystem: true
  runAsNonRoot: true
